sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install
before_script:
  - git config --global user.email "rhkdrmfh@gmail.com"
  - git config --global user.name "LeeGwangYong"

script: bundle exec rake site:deploy #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "Eme19+xGLf9ltAw0cCayYzW5JW7XOi8zDKWdfG2nojWyaMuWj1CG1VqPzfUwp1/HfEzUmer0Eg0Fx7X1Q8jqTx8eFyO4yxwsiTKQYKJyil6CMtHTalRSzrPSNplYNV5vnz5sOQGC0o95gjAQvQWVsGPjwEE7UWxSv9r4OVE5x/Dm7zpWnCgiHE8GfY9eZs8rzY39DK0iyvWycOECdsx9AtEVSI4nL0pBzMgAbDssvzbzSgSEYVdaP3zuTmw/crQ/t9xpi1esvQjbIWDJEKWwwLpOQWOgx2ytZ+5dx538hispXMTDu0iwgabA6ZlgNhanHHPPaI/jaCuN3G40XowkfsOz0EQjd0d1oU5gz0L08PrJOhXzjLhCDwnBMBaeMoiEGU5AFWsUDCb/riI25ZjJ1cdmXw+WWUF2hu/jTUiEUe1+A3BuPI4u36MuTd7xlrjCQKqD5lA8KUwMO/qigkuPSQ5Dt2IwZWsu3SGyNCm7BSn0/zGauszEesTcpuPHVqmXSqnEQZ0qIhjitQ2l/biwiES7UOPq6BiFRG/IyH3FW5NivFHiUnuYnuJABXuLUhnK68GqdAoDX6MQg6RW3y3mN1oPd76SYxkyIXSecGDmFg7GS1+DiUh7mdJuyr9J8dOILYAY7YP02G2Wtmpa1Qr4BKlLQWO/N7SToEJQubBqhkg="
branches:
  only:
    - master
