sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "rhkdrmfh@gmail.com"
  - git config --global user.name "LeeGwangYong"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "gaw1xjflq3wL28Q234O84D7RFUNhfeCynvwLYQEwsuZe7x91j4TjUNA8S0VhuuynpHlSm8DVW6S7fG4nj+m5u6v7lgj6NUE7yh9xwIq0SGWIv43t0hbQ6doQ/e/45kCiI5o0jyA72mOwbaE54bJ7NKaigzLScivBD6z5cgd5pI0trsaUT8SaKeSRm488G4yBmsl1j/1z0GmkX6Eg1Y07q8o3bB2DQk7pea/mmXSM+DgaEpOZYZ2fUezoDcgcaq2SkjPo499lbF9zNsa8CZWlQ8etkkKjQMFlkES4drY3S3SVQ+lQ5YHB7JoW9+W7rjOEDN82Ce8Wam7VCuw8+xIfKyYRZQ5gWkD5N/rcAxVmIwZxJ+ldMVIVcUN5IB4hXR6+Iqu5gVUmcbi5vhhdMX5KWwIo8eBFRvDpG3LpWdUd2O1rP7MkLJnUeXIOnXSnSIaj80H0wGLwuVaET5wPKreU4LnX9i0rskuTXZkzXvtaRXRDH12LE+olp7ZhwgqJkJZbYx5jW8rEf2oshxeD9SgaWk9WyvJuz9b/os6Nh+YAnvZw99Ik2WR8rmgZTzu3wqM/NLxWFt0Yn3L2hm5+IcnGEv+c0j/+nBp4HYzaFsrb3DrM6SUwPolJvRBRhFBRZoHxMawMr4tHYRXOJ/52+N+MjKKmetuETMKuvmwLPMGSJyg="
branches:
  only:
    - master